In [1]:
import pandas as pd
df=pd.read_csv("C:\do not open\Helloworld\Customer_Shopping_Behaviour\customer_shopping_behavior_2000.csv.csv")

<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\Dell\AppData\Local\Temp\ipykernel_3964\1556606712.py:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df=pd.read_csv("C:\do not open\Helloworld\Customer_Shopping_Behaviour\customer_shopping_behavior_2000.csv.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,50,Male,Sandals,Footwear,210,Jacksonville,M,Black,Summer,3.6,Yes,Express,No,NO,6,Venmo,Annually
1,2,33,Female,Shorts,Clothing,276,San Antonio,L,Beige,Fall,4.0,Yes,Express,No,NO,27,Bank Transfer,Monthly
2,3,31,Male,Sneakers,Footwear,50,Washington,XL,Green,Winter,5.0,No,Standard,No,NO,23,Debit Card,Annually
3,4,70,Female,Scarf,Accessories,461,Jacksonville,M,Green,Summer,3.2,No,Store Pickup,Yes,NO,3,Credit Card,Fortnightly
4,5,27,Male,Dress,Clothing,489,Charlotte,XL,Brown,Spring,3.1,No,Standard,Yes,YES,24,Credit Card,Quarterly

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             2000 non-null   int64
 1   Age                     2000 non-null   int64
 2   Gender                  2000 non-null   str
 3   Item Purchased          2000 non-null   str
 4   Category                2000 non-null   str
 5   Purchase Amount (USD)   2000 non-null   int64
 6   Location                2000 non-null   str
 7   Size                    2000 non-null   str
 8   Color                   2000 non-null   str
 9   Season                  2000 non-null   str
 10  Review Rating           1963 non-null   float64
 11  Subscription Status     2000 non-null   str
 12  Shipping Type           2000 non-null   str
 13  Discount Applied        2000 non-null   str
 14  Promo Code Used         2000 non-null   str
 15  Previous Purchases      2000 non-null   int64
 16  Payment Method          2000 non-null   str
 17  Frequency of Purchases  2000 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 281.4 KB

In [4]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,2000.000000,2000.000000,2000,2000,2000,2000.000000,2000,2000,2000,2000,1963.000000,2000,2000,2000,2000,2000.00000,2000,2000
unique,NaN,NaN,2,22,4,NaN,20,4,10,4,NaN,2,5,2,2,NaN,6,5
top,NaN,NaN,Female,Jeans,Clothing,NaN,Jacksonville,M,Brown,Fall,NaN,No,Standard,No,NO,NaN,PayPal,Monthly
freq,NaN,NaN,1060,195,1094,NaN,116,694,217,535,NaN,1238,410,1356,1421,NaN,345,628
mean,1000.500000,44.118500,NaN,NaN,NaN,258.196000,NaN,NaN,NaN,NaN,3.766633,NaN,NaN,NaN,NaN,25.35550,NaN,NaN
std,577.494589,15.023126,NaN,NaN,NaN,140.751622,NaN,NaN,NaN,NaN,0.717612,NaN,NaN,NaN,NaN,14.35375,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.00000,NaN,NaN
25%,500.750000,31.000000,NaN,NaN,NaN,140.000000,NaN,NaN,NaN,NaN,3.200000,NaN,NaN,NaN,NaN,13.00000,NaN,NaN
50%,1000.500000,44.000000,NaN,NaN,NaN,258.500000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.00000,NaN,NaN
75%,1500.250000,57.000000,NaN,NaN,NaN,377.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.00000,NaN,NaN
max,2000.000000,70.000000,NaN,NaN,NaN,500.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.00000,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x:x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","-")
df.rename(columns={"Purchase Amount (USD)" : "purchase_amount"})

,customer-id,age,gender,item-purchased,category,purchase-amount-(usd),location,size,color,season,review-rating,subscription-status,shipping-type,discount-applied,promo-code-used,previous-purchases,payment-method,frequency-of-purchases
0,1,50,Male,Sandals,Footwear,210,Jacksonville,M,Black,Summer,3.6,Yes,Express,No,NO,6,Venmo,Annually
1,2,33,Female,Shorts,Clothing,276,San Antonio,L,Beige,Fall,4.0,Yes,Express,No,NO,27,Bank Transfer,Monthly
2,3,31,Male,Sneakers,Footwear,50,Washington,XL,Green,Winter,5.0,No,Standard,No,NO,23,Debit Card,Annually
3,4,70,Female,Scarf,Accessories,461,Jacksonville,M,Green,Summer,3.2,No,Store Pickup,Yes,NO,3,Credit Card,Fortnightly
4,5,27,Male,Dress,Clothing,489,Charlotte,XL,Brown,Spring,3.1,No,Standard,Yes,YES,24,Credit Card,Quarterly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,54,Male,Sandals,Footwear,121,Seattle,S,Red,Spring,2.9,Yes,Express,No,NO,13,PayPal,Fortnightly
1996,1997,52,Female,Shorts,Clothing,411,Austin,L,Yellow,Summer,3.3,No,Next Day,No,NO,19,Venmo,Annually
1997,1998,62,Male,Shorts,Clothing,211,Seattle,L,Black,Summer,4.9,No,Express,No,NO,31,Bank Transfer,Fortnightly
1998,1999,55,Male,Running Shoes,Footwear,423,Columbus,M,Pink,Winter,3.6,No,Standard,No,NO,35,Debit Card,Monthly
1999,2000,61,Female,T-shirt,Clothing,87,Columbus,XL,Black,Fall,3.6,Yes,2-Day,Yes,NO,19,Venmo,Quarterly

In [9]:
df.columns

Index(['customer-id', 'age', 'gender', 'item-purchased', 'category',
       'purchase-amount-(usd)', 'location', 'size', 'color', 'season',
       'review-rating', 'subscription-status', 'shipping-type',
       'discount-applied', 'promo-code-used', 'previous-purchases',
       'payment-method', 'frequency-of-purchases'],
      dtype='str')

In [10]:
#create a column age_group
labels=["Young Adult","Adult","Middle_aged","Senior"]
df["age_group"]=pd.qcut(df["age"],q=4,labels=labels)

In [11]:
df[["age","age_group"]].head(10)

   age    age_group
0   50  Middle_aged
1   33        Adult
2   31  Young Adult
3   70       Senior
4   27  Young Adult
5   28  Young Adult
6   67       Senior
7   47  Middle_aged
8   20  Young Adult
9   40        Adult

In [12]:
#purchase frequency days
frequency_mapping = {
    "fortnightly": 14,
    "weekly": 7,
    "Monthly": 30,
    "Quarterly": 90,
    "Bi_weekly": 14,
    "Annually": 365,
    "Every 3 month": 90
}

df["purchase_frequency_days"] = (
    df["frequency-of-purchases"].map(frequency_mapping)
)

In [13]:
print(df[["frequency-of-purchases",
          "purchase_frequency_days"]].head(10))

  frequency-of-purchases  purchase_frequency_days
0               Annually                    365.0
1                Monthly                     30.0
2               Annually                    365.0
3            Fortnightly                      NaN
4              Quarterly                     90.0
5               Annually                    365.0
6              Quarterly                     90.0
7            Fortnightly                      NaN
8            Fortnightly                      NaN
9            Fortnightly                      NaN

In [14]:
df[["discount-applied","promo-code-used"]].head(10)

  discount-applied promo-code-used
0               No              NO
1               No              NO
2               No              NO
3              Yes              NO
4              Yes             YES
5               No             YES
6               No              NO
7               No              NO
8               No              NO
9               No              NO

In [15]:
print(df.columns.tolist())

['customer-id', 'age', 'gender', 'item-purchased', 'category', 'purchase-amount-(usd)', 'location', 'size', 'color', 'season', 'review-rating', 'subscription-status', 'shipping-type', 'discount-applied', 'promo-code-used', 'previous-purchases', 'payment-method', 'frequency-of-purchases', 'age_group', 'purchase_frequency_days']

In [16]:
df["discount-applied"]==df["promo-code-used"].all()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: discount-applied, Length: 2000, dtype: bool

In [17]:
df.drop("promo-code-used",axis=1)

,customer-id,age,gender,item-purchased,category,purchase-amount-(usd),location,size,color,season,review-rating,subscription-status,shipping-type,discount-applied,previous-purchases,payment-method,frequency-of-purchases,age_group,purchase_frequency_days
0,1,50,Male,Sandals,Footwear,210,Jacksonville,M,Black,Summer,3.6,Yes,Express,No,6,Venmo,Annually,Middle_aged,365.0
1,2,33,Female,Shorts,Clothing,276,San Antonio,L,Beige,Fall,4.0,Yes,Express,No,27,Bank Transfer,Monthly,Adult,30.0
2,3,31,Male,Sneakers,Footwear,50,Washington,XL,Green,Winter,5.0,No,Standard,No,23,Debit Card,Annually,Young Adult,365.0
3,4,70,Female,Scarf,Accessories,461,Jacksonville,M,Green,Summer,3.2,No,Store Pickup,Yes,3,Credit Card,Fortnightly,Senior,NaN
4,5,27,Male,Dress,Clothing,489,Charlotte,XL,Brown,Spring,3.1,No,Standard,Yes,24,Credit Card,Quarterly,Young Adult,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,54,Male,Sandals,Footwear,121,Seattle,S,Red,Spring,2.9,Yes,Express,No,13,PayPal,Fortnightly,Middle_aged,NaN
1996,1997,52,Female,Shorts,Clothing,411,Austin,L,Yellow,Summer,3.3,No,Next Day,No,19,Venmo,Annually,Middle_aged,365.0
1997,1998,62,Male,Shorts,Clothing,211,Seattle,L,Black,Summer,4.9,No,Express,No,31,Bank Transfer,Fortnightly,Senior,NaN
1998,1999,55,Male,Running Shoes,Footwear,423,Columbus,M,Pink,Winter,3.6,No,Standard,No,35,Debit Card,Monthly,Middle_aged,30.0
1999,2000,61,Female,T-shirt,Clothing,87,Columbus,XL,Black,Fall,3.6,Yes,2-Day,Yes,19,Venmo,Quarterly,Senior,90.0

In [18]:
df.columns

Index(['customer-id', 'age', 'gender', 'item-purchased', 'category',
       'purchase-amount-(usd)', 'location', 'size', 'color', 'season',
       'review-rating', 'subscription-status', 'shipping-type',
       'discount-applied', 'promo-code-used', 'previous-purchases',
       'payment-method', 'frequency-of-purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [ ]:
#connect to sql
import mysql.connector
import pandas as pd

# Database connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",  # Enter your MySQL password
    database="customer_behaviour",
    port=3306
)

if conn.is_connected():
    print("Database connected successfully!")

Database connected successfully!

In [20]:
%pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.1.6-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Downloading sqlalchemy-2.1.6-cp314-cp314-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   ----------------- ---------------------- 1.0/2.4 MB 1.9 MB/s eta 0:00:01
   --------------------- ------------------ 1.3/2.4 MB 1.9 MB/s eta 0:00:01
   ------------------------------ --------- 1.8/2.4 MB 1.9 MB/s eta 0:00:01
   ------------------------------ --------- 1.8/2.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------- ----- 2.1/2.4 MB 1.5 MB/s eta 0:00:01
   ---------------------------------- ----- 2.1/2.4 MB 1.5 MB/s eta 0:00:01
   ---------------------------------- ----- 2.1/2.4 MB 1.5 MB/s eta 0:00:01
   -------------------------------------- - 2.4/2.4 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 1.1 MB/s  0:00:02
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: sqlalchemy, pymysql

   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [pymysql]
   -------------------- ------------------- 1/2 [pymysql]
   ---------------------------------------- 2/2 [pymysql]

Successfully installed pymysql-1.2.3 sqlalchemy-2.1.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
from sqlalchemy import create_engine

username = "root"
password = "root"  # Enter your MySQL password
host = "localhost"
database = "customer_behaviour"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:3306/{database}"
)

# Test the connection
with engine.connect() as connection:
    print("MySQL database connected successfully!")

MySQL database connected successfully!

In [25]:
# Step 2
table_name = "customer"

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'")

Data successfully loaded into table 'customer' in database 'customer_behaviour'